name: Update Cloudflare Proxy IP

on:
  schedule:
    - cron: '*/30 * * * *'  # 每三十分钟执行一次（UTC时间）
  workflow_dispatch:     # 支持手动触发

jobs:
  update-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整提交历史

      - name: Fetch New Proxy IP
        id: get_ip
        run: |
          # 调用 API 获取新 IP，保留响应中的 IP 地址
          NEW_IP=$(curl -s "https://ipdb.api.030101.xyz/?type=bestproxy" \
            -H "accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" \
            -H "accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6" \
            -H "priority: u=0, i" \
            -H "upgrade-insecure-requests: 1")
          echo "NEW_IP=$NEW_IP" >> $GITHUB_ENV

      - name: Replace IP in File
        run: |
          # 定位目标文件路径
          FILE_PATH="cloudflare_auto/ipurl.txt"
          
          # 使用 sed 替换第一行末尾的 IP 地址
          sed -i "1s|@[0-9.]*$|@${{ env.NEW_IP }}|" "$FILE_PATH"
          
          # 检查是否修改成功
          echo "Updated File Content:"
          head -n 1 "$FILE_PATH"

      - name: Commit Changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add cloudflare_auto/ipurl.txt
          git commit -m "Auto-Update: Replace proxy IP to ${{ env.NEW_IP }}"
          git push
